### PR TITLE
fix(legacy-preset-chart-nvd3): time compare and stacked area tooltips

### LINKED ISSUE #795: Timeseries percent change chart does not show correct date in tooltip
**Describe the bug**

> On the "timeseries percent change" superset visualization, the date in the tooltip shows up as `0Nan`

**To Reproduce**

image

**Expected behavior**
`0Nan` should be replaced with date. 

**Screenshots**
Pasted_Image_9_22_20__3_57_PM

### PR DESCRIPTION
**Pull request by kristw**
🐛 Bug Fix

Fix #795 and #799 

# Fix 795

For the `compare` chart in Superset or the `cumulativeLineChart` (from nvd3), the time is passed to the tooltip as a formatted time string. There is no way to customize the format unlike other chart types. Trying to apply a time format function on a string resulting in `0NaN`. 

This fix will at least make the tooltip has same format with the x-axis, better than `0NaN`.

Pasted_Image_12_2_20__6_01_PM

Also add storybook example for verification

# Fix 799

The stacked area chart has 3 stacked style, the `expand` style pass data to tooltip slightly differently from the other two. It does not include a total row. This PR fix the total number calculation for `expand` case.

Pasted_Image_12_2_20__6_00_PM

### CODE REVIEW

File: plugins/legacy-preset-chart-nvd3/src/utils.js [hunk 1]
```diff
@@ -132,8 +132,40 @@ export function generateRichLineTooltipContent(d, timeFormatter, valueFormatter)
   return dompurify.sanitize(tooltip);
 }
 
-export function generateAreaChartTooltipContent(d, timeFormatter, valueFormatter) {
-  const total = d.series[d.series.length - 1].value;
+export function generateCompareTooltipContent(d, valueFormatter) {
+  let tooltip = '';
+  tooltip +=
+    "<table><thead><tr><td colspan='3'>" +
+    `<strong class='x-value'>${d.value}</strong>` +
```
Comment (ktmud) [inline plugins/legacy-preset-chart-nvd3/src/utils.js:139]: Template literals support multiline strings directly so the manual concatenation might not be needed.

**Review by ktmud — APPROVED** [review]
lgtm with one style nit

File: plugins/legacy-preset-chart-nvd3/src/utils.js (hunk 1 above)
Comment (kristw) [reply plugins/legacy-preset-chart-nvd3/src/utils.js:139]: The other tooltip generator use this style so I am gonna leave it same for now. 
Don't want to change all of them yet. 
Also to avoid potential unintentional spacing from space characters between tags.
