### PR TITLE
Remove unnecessary export types and reorganize types

### LINKED ISSUE #94: Warning "export 'xxx' was not found in '...'"
**Describe the bug**

Warning message about missing types. The types code are strip when transpile to javascript, but the exports are not.

```
WARNING in ./node_modules/@superset-ui/core/esm/index.js 1:178-260
"export 'RegistryConfig' was not found in './models/Registry'
 @ ./node_modules/@superset-ui/color/esm/CategoricalColorScale.js
 @ ./node_modules/@superset-ui/color/esm/CategoricalColorNamespace.js
 @ ./node_modules/@superset-ui/color/esm/index.js
 @ ./src/setup/setupColors.js
 @ ./src/preamble.js
 @ multi (webpack)-dev-server/client?http://localhost:9000 (webpack)/hot/dev-server.js babel-polyfill ./src/preamble.js

WARNING in ./node_modules/@superset-ui/core/esm/index.js 1:260-368
"export 'RegistryWithDefaultKeyConfig' was not found in './models/RegistryWithDefaultKey'
 @ ./node_modules/@superset-ui/color/esm/CategoricalColorScale.js
 @ ./node_modules/@superset-ui/color/esm/CategoricalColorNamespace.js
 @ ./node_modules/@superset-ui/color/esm/index.js
 @ ./src/setup/setupColors.js
 @ ./src/preamble.js
 @ multi (webpack)-dev-server/client?http://localhost:9000 (webpack)/hot/dev-server.js babel-polyfill ./src/preamble.js

WARNING in ./node_modules/@superset-ui/color/esm/index.js 1:459-542
"export 'SequentialSchemeConfig' was not found in './SequentialScheme'
 @ ./src/setup/setupColors.js
 @ ./src/preamble.js
 @ multi (webpack)-dev-server/client?http://localhost:9000 (webpack)/hot/dev-server.js babel-polyfill ./src/preamble.js

WARNING in ./node_modules/@superset-ui/connection/esm/index.js 1:42-122
"export 'SupersetClientInterface' was not found in './SupersetClient'
 @ ./src/setup/setupClient.js
 @ ./src/preamble.js
 @ multi (webpack)-dev-server/client?http://localhost:9000 (webpack)/hot/dev-server.js babel-polyfill ./src/preamble.js
```

See more details of similar issues.
https://github.com/webpack/webpack/issues/7378

**To Reproduce**
Use the `@superset-ui` packages (that was written in TypeScript) in another app.

**Expected behavior**
Build successfully without warning.

**Screenshots**

**Environment (please complete the following information):**
 - superset-ui version: 0.9.3
 - Node version: 10.10
 - npm version: 6.4.1

### PR DESCRIPTION
**Pull request by kristw**
🏠 Internal

This is to fix #94 by removing the exported type that are not necessary and move the ones that are exported to `types.ts` or `types/xxx.ts`.

Also clean up some styling by replacing `Array<xxx>` with `xxx[]`

### CODE REVIEW

File: packages/superset-ui-chart/src/index.ts [hunk 1]
```diff
@@ -1,12 +1,7 @@
-export { ChartClient, ChartClientConfig } from './clients/ChartClient';
-export { default as ChartMetadata, ChartMetadataConfig } from './models/ChartMetadata';
-export {
-  default as ChartPlugin,
-  ChartPluginConfig,
-  BuildQueryFunction,
-  TransformPropsFunction,
-} from './models/ChartPlugin';
-export { default as ChartProps, ChartPropsConfig } from './models/ChartProps';
+export { default as ChartClient } from './clients/ChartClient';
```
Comment (xtinec) [inline packages/superset-ui-chart/src/index.ts]: 💯 This is easier to read!

File: packages/superset-ui-chart/src/index.ts [hunk 2]
```diff
@@ -21,6 +16,10 @@ export {
   default as getChartTransformPropsRegistry,
 } from './registries/ChartTransformPropsRegistrySingleton';
 
-export { QueryContext, buildQueryContext } from './query/buildQueryContext';
-export { DatasourceType, DatasourceKey } from './query/DatasourceKey';
-export { FormData } from './query/FormData';
+export { default as buildQueryContext } from './query/buildQueryContext';
+export { default as DatasourceKey } from './query/DatasourceKey';
+
+export * from './types/Annotation';
```
Comment (williaster) [inline packages/superset-ui-chart/src/index.ts]: generally I think it's good to be explicit with exports for readability + ensuring that there is no conflict / overriding of variables (unsure if that would error or cause subtle bugs for types)

**Comment by williaster** [comment]
thanks for making this change!
